chains:
  - name: injective-1
    type: injective
    image: ghcr.io/cosmology-tech/starship/injective:v1.11.5
    numValidators: 1
    ports:
      rest: 1318
      rpc: 26658

registry:
  enabled: true
  ports:
    rest: 8081
  resources:
    cpu: "0.1"
    memory: "100M"

exposer:
  resources:
    cpu: "0.1"
    memory: "100M"

explorer:
  enabled: true
  ports:
    rest: 8080
